train_dataset:
  name: stanford2d3d
  root_path: /hpc2hdd/home/zcao740/Documents/Dataset/Stanford2D3D/
  list_path: /hpc2hdd/home/zcao740/Documents/Github/CRF360D/datasets/stanford2d3d_train.txt
  args:
    height: 512
    width: 1024
    repeat: 1
    augment_color: True
    augment_flip: True
    augment_rotation: True
  batch_size: 4
  num_workers: 4

val_dataset:
  name: stanford2d3d
  root_path: /hpc2hdd/home/zcao740/Documents/Dataset/Stanford2D3D/
  list_path: /hpc2hdd/home/zcao740/Documents/Github/CRF360D/datasets/stanford2d3d_val.txt
  args:
    height: 512
    width: 1024
    repeat: 1
    augment_color: False
    augment_flip: False
    augment_rotation: False
  batch_size: 1
  num_workers: 4

model:
  name: panocrf
  args:
    encoder: efficientnet
    min_depth: 0.1
    max_depth: 8.0
    depth: 2
    rotation: True
    localconv: True
    interact: False

loss: silog

optimizer:
  lr: 1.e-4
epoch_max: 60
log_frequency: 1000

epoch_val: 1
epoch_save: 10





