test_dataset:
  name: matterport3d
  root_path: /hpc2hdd/home/zcao740/Documents/Dataset/Matterport3D/
  list_path: /hpc2hdd/home/zcao740/Documents/Github/CRF360D/datasets/matterport3d_test.txt
  args:
    height: 512
    width: 1024
    repeat: 1
    augment_color: False
    augment_flip: False
    augment_rotation: False
  batch_size: 1
  num_workers: 4

model:
  name: panocrf
  args:
    encoder: efficientnet
    min_depth: 0.1
    max_depth: 10.0
    depth: 2
    rotation: True
    localconv: True
    interact: False

median_align: False

load_weights_dir: ./tmp/matterport3d/




